version: '3.8'

services:
  nest-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=223.4.248.176
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Qq123456!
      - DB_DATABASE=nest_db
      - YOUDAO_APP_KEY=20220529001233310
      - YOUDAO_APP_SECRET=yuM_bOR5cbjZVttocWs1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    container_name: nest-server-app